from dotenv import load_dotenv
import os

load_dotenv()

AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")
AZURE_OPENAI_DEPLOYMENT_FALLBACK = os.getenv("AZURE_OPENAI_DEPLOYMENT_FALLBACK")
AZURE_OPENAI_API_VERSION_FALLBACK = os.getenv("AZURE_OPENAI_API_VERSION_FALLBACK")

QDRANT_URL = "http://localhost:6333"
QDRANT_PORT = 6333

COLLECTION_SUMMARIES = "summaries"
COLLECTION_CACHE = "rag_semantic_cache1"

CHUNKS_DIR = "chunks"
INDEX_FILE = "output1.json"